
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Build and push protoc
      uses: docker/build-push-action@v1
      with:
        repository: AZPool/azpool.actions
        dockerfile: protoc/Dockerfile
        tag_with_sha: true
        tags: latest
